
services:
  frontend:
    build: ./frontend
    container_name: fe
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: be
    ports:
      - "5001:5000"
    depends_on:
     - mongo

  mongo:
    image: mongo:5.0
    container_name: db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: